version: "3.7"

services:

  flask1:
    build: ./flask
    container_name: flask1
    restart: always
    environment:
      - PORT=8080
      - DATABASE=users.db
    expose:
      - 8080

  flask2:
    build: ./flask
    container_name: flask2
    restart: always
    environment:
      - PORT=8081
      - DATABASE=users.db
    expose:
      - 8081

  flask3:
    build: ./flask
    container_name: flask3
    restart: always
    environment:
      - PORT=8082
      - DATABASE=users.db
    expose:
      - 8082

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
