version: "3.7"

services:

  flask1:
    build: ./flask_rest
    container_name: flask1
    restart: always
    environment:
      - PORT=8080
    expose:
      - 8080

  flask2:
    build: ./flask_rest
    container_name: flask2
    restart: always
    environment:
      - PORT=8081
    expose:
      - 8081

  flask3:
    build: ./flask_rest
    container_name: flask3
    restart: always
    environment:
      - PORT=8082
    expose:
      - 8082

  flask_db:
    build: ./flask_db
    container_name: flask_db
    restart: always
    environment:
      - DATABASE=users.db
    expose:
      - 6000

  flask_gui:
    build: ./flask_GUI
    container_name: flask_gui
    restart: always
    expose:
      - 5000

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
